# Generated by Django 5.1.7 on 2025-03-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Authentication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("firstname", models.CharField(max_length=50)),
                ("surname", models.CharField(max_length=50)),
                ("regnum", models.CharField(max_length=20, unique=True)),
                ("password", models.CharField(max_length=128)),
                ("confirm_password", models.CharField(max_length=128)),
            ],
        ),
    ]
