# Generated by Django 5.1.7 on 2025-05-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker_Dashboard', '0002_authentication_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authentication',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='authentication',
            name='regnum',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
