# Generated by Django 5.1.7 on 2025-05-03 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker_Dashboard', '0003_alter_authentication_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authentication',
            name='confirm_password',
        ),
    ]
